#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 79
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_DOT = 1,
  anon_sym_COLON_DASH = 2,
  anon_sym_COMMA = 3,
  anon_sym_PIPE_GT = 4,
  anon_sym_PLUS = 5,
  anon_sym_DASH = 6,
  anon_sym_STAR = 7,
  anon_sym_SLASH = 8,
  anon_sym_AT = 9,
  anon_sym_LPAREN = 10,
  anon_sym_RPAREN = 11,
  anon_sym_LT_EQ = 12,
  anon_sym_GT_EQ = 13,
  anon_sym_LT = 14,
  anon_sym_GT = 15,
  anon_sym_LBRACK = 16,
  anon_sym_PIPE = 17,
  anon_sym_RBRACK = 18,
  sym_unquoted_atom = 19,
  anon_sym_SQUOTE = 20,
  aux_sym_quoted_atom_token1 = 21,
  sym_escape_sequence = 22,
  sym_variable = 23,
  sym_number = 24,
  anon_sym_PERCENT = 25,
  aux_sym_line_comment_token1 = 26,
  anon_sym_SLASH_STAR = 27,
  aux_sym_block_comment_token1 = 28,
  sym_source_file = 29,
  sym_clause = 30,
  sym_fact = 31,
  sym_rule = 32,
  sym_goals = 33,
  sym_term = 34,
  sym_pipe_expr = 35,
  sym_add_expr = 36,
  sym_mul_expr = 37,
  sym_primary_term = 38,
  sym_default_var = 39,
  sym_paren_expr = 40,
  sym_range_var = 41,
  sym_comp_op = 42,
  sym_list = 43,
  sym_struct = 44,
  sym_atom = 45,
  sym_quoted_atom = 46,
  sym_line_comment = 47,
  sym_block_comment = 48,
  aux_sym_source_file_repeat1 = 49,
  aux_sym_goals_repeat1 = 50,
  aux_sym_pipe_expr_repeat1 = 51,
  aux_sym_add_expr_repeat1 = 52,
  aux_sym_mul_expr_repeat1 = 53,
  aux_sym_quoted_atom_repeat1 = 54,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DOT] = ".",
  [anon_sym_COLON_DASH] = ":-",
  [anon_sym_COMMA] = ",",
  [anon_sym_PIPE_GT] = "|>",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_AT] = "@",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LBRACK] = "[",
  [anon_sym_PIPE] = "|",
  [anon_sym_RBRACK] = "]",
  [sym_unquoted_atom] = "unquoted_atom",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_atom_token1] = "quoted_atom_token1",
  [sym_escape_sequence] = "escape_sequence",
  [sym_variable] = "variable",
  [sym_number] = "number",
  [anon_sym_PERCENT] = "%",
  [aux_sym_line_comment_token1] = "line_comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_block_comment_token1] = "block_comment_token1",
  [sym_source_file] = "source_file",
  [sym_clause] = "clause",
  [sym_fact] = "fact",
  [sym_rule] = "rule",
  [sym_goals] = "goals",
  [sym_term] = "term",
  [sym_pipe_expr] = "pipe_expr",
  [sym_add_expr] = "add_expr",
  [sym_mul_expr] = "mul_expr",
  [sym_primary_term] = "primary_term",
  [sym_default_var] = "default_var",
  [sym_paren_expr] = "paren_expr",
  [sym_range_var] = "range_var",
  [sym_comp_op] = "comp_op",
  [sym_list] = "list",
  [sym_struct] = "struct",
  [sym_atom] = "atom",
  [sym_quoted_atom] = "quoted_atom",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_goals_repeat1] = "goals_repeat1",
  [aux_sym_pipe_expr_repeat1] = "pipe_expr_repeat1",
  [aux_sym_add_expr_repeat1] = "add_expr_repeat1",
  [aux_sym_mul_expr_repeat1] = "mul_expr_repeat1",
  [aux_sym_quoted_atom_repeat1] = "quoted_atom_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_COLON_DASH] = anon_sym_COLON_DASH,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_PIPE_GT] = anon_sym_PIPE_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_unquoted_atom] = sym_unquoted_atom,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_atom_token1] = aux_sym_quoted_atom_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_variable] = sym_variable,
  [sym_number] = sym_number,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [aux_sym_line_comment_token1] = aux_sym_line_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_block_comment_token1] = aux_sym_block_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym_clause] = sym_clause,
  [sym_fact] = sym_fact,
  [sym_rule] = sym_rule,
  [sym_goals] = sym_goals,
  [sym_term] = sym_term,
  [sym_pipe_expr] = sym_pipe_expr,
  [sym_add_expr] = sym_add_expr,
  [sym_mul_expr] = sym_mul_expr,
  [sym_primary_term] = sym_primary_term,
  [sym_default_var] = sym_default_var,
  [sym_paren_expr] = sym_paren_expr,
  [sym_range_var] = sym_range_var,
  [sym_comp_op] = sym_comp_op,
  [sym_list] = sym_list,
  [sym_struct] = sym_struct,
  [sym_atom] = sym_atom,
  [sym_quoted_atom] = sym_quoted_atom,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_goals_repeat1] = aux_sym_goals_repeat1,
  [aux_sym_pipe_expr_repeat1] = aux_sym_pipe_expr_repeat1,
  [aux_sym_add_expr_repeat1] = aux_sym_add_expr_repeat1,
  [aux_sym_mul_expr_repeat1] = aux_sym_mul_expr_repeat1,
  [aux_sym_quoted_atom_repeat1] = aux_sym_quoted_atom_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_unquoted_atom] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_atom_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_block_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_fact] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_goals] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_pipe_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_add_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_mul_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_term] = {
    .visible = true,
    .named = true,
  },
  [sym_default_var] = {
    .visible = true,
    .named = true,
  },
  [sym_paren_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_range_var] = {
    .visible = true,
    .named = true,
  },
  [sym_comp_op] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_goals_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pipe_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_add_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mul_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_atom_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      if (lookahead == '%') ADVANCE(37);
      if (lookahead == '\'') ADVANCE(30);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == '+') ADVANCE(15);
      if (lookahead == ',') ADVANCE(13);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == ':') ADVANCE(6);
      if (lookahead == '<') ADVANCE(24);
      if (lookahead == '>') ADVANCE(25);
      if (lookahead == '@') ADVANCE(19);
      if (lookahead == '[') ADVANCE(26);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == ']') ADVANCE(28);
      if (lookahead == '|') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(35);
      END_STATE();
    case 1:
      if (lookahead == '%') ADVANCE(39);
      if (lookahead == '\'') ADVANCE(30);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 2:
      if (lookahead == '%') ADVANCE(38);
      if (lookahead == '*') ADVANCE(48);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(2);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(44);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(48);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(45);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == '\n' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 't') ADVANCE(34);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '%') ADVANCE(37);
      if (lookahead == '\'') ADVANCE(30);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '[') ADVANCE(26);
      if (lookahead == ']') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(35);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON_DASH);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_PIPE_GT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(44);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(22);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(23);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '>') ADVANCE(14);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_unquoted_atom);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == '%') ADVANCE(39);
      if (lookahead == '/') ADVANCE(32);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == '*') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == '*') ADVANCE(48);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '%') ADVANCE(40);
      if (lookahead == '/') ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '*') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead == '*') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(4);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(33);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(43);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_block_comment_token1);
      if (lookahead == '*') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(4);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 9},
  [2] = {.lex_state = 9},
  [3] = {.lex_state = 9},
  [4] = {.lex_state = 9},
  [5] = {.lex_state = 9},
  [6] = {.lex_state = 9},
  [7] = {.lex_state = 9},
  [8] = {.lex_state = 9},
  [9] = {.lex_state = 9},
  [10] = {.lex_state = 9},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 9},
  [15] = {.lex_state = 9},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 9},
  [46] = {.lex_state = 9},
  [47] = {.lex_state = 9},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 9},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 9},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 9},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 9},
  [70] = {.lex_state = 9},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 41},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {(TSStateId)(-1)},
  [78] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_line_comment] = STATE(0),
    [sym_block_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_COLON_DASH] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_PIPE_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_unquoted_atom] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [1] = {
    [sym_source_file] = STATE(65),
    [sym_clause] = STATE(47),
    [sym_fact] = STATE(46),
    [sym_rule] = STATE(46),
    [sym_term] = STATE(64),
    [sym_pipe_expr] = STATE(50),
    [sym_add_expr] = STATE(44),
    [sym_mul_expr] = STATE(40),
    [sym_primary_term] = STATE(19),
    [sym_default_var] = STATE(31),
    [sym_paren_expr] = STATE(31),
    [sym_range_var] = STATE(31),
    [sym_list] = STATE(31),
    [sym_struct] = STATE(31),
    [sym_atom] = STATE(17),
    [sym_quoted_atom] = STATE(22),
    [sym_line_comment] = STATE(1),
    [sym_block_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [sym_unquoted_atom] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [sym_variable] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_PERCENT] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 20,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(26), 1,
      anon_sym_LBRACK,
    ACTIONS(29), 1,
      sym_unquoted_atom,
    ACTIONS(32), 1,
      anon_sym_SQUOTE,
    ACTIONS(35), 1,
      sym_variable,
    ACTIONS(38), 1,
      sym_number,
    STATE(17), 1,
      sym_atom,
    STATE(19), 1,
      sym_primary_term,
    STATE(22), 1,
      sym_quoted_atom,
    STATE(40), 1,
      sym_mul_expr,
    STATE(44), 1,
      sym_add_expr,
    STATE(47), 1,
      sym_clause,
    STATE(50), 1,
      sym_pipe_expr,
    STATE(64), 1,
      sym_term,
    STATE(46), 2,
      sym_fact,
      sym_rule,
    STATE(2), 3,
      sym_line_comment,
      sym_block_comment,
      aux_sym_source_file_repeat1,
    STATE(31), 5,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [68] = 21,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      aux_sym_source_file_repeat1,
    STATE(17), 1,
      sym_atom,
    STATE(19), 1,
      sym_primary_term,
    STATE(22), 1,
      sym_quoted_atom,
    STATE(40), 1,
      sym_mul_expr,
    STATE(44), 1,
      sym_add_expr,
    STATE(47), 1,
      sym_clause,
    STATE(50), 1,
      sym_pipe_expr,
    STATE(64), 1,
      sym_term,
    STATE(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(46), 2,
      sym_fact,
      sym_rule,
    STATE(31), 5,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [138] = 18,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(43), 1,
      anon_sym_RBRACK,
    STATE(17), 1,
      sym_atom,
    STATE(19), 1,
      sym_primary_term,
    STATE(22), 1,
      sym_quoted_atom,
    STATE(40), 1,
      sym_mul_expr,
    STATE(44), 1,
      sym_add_expr,
    STATE(50), 1,
      sym_pipe_expr,
    STATE(53), 1,
      sym_term,
    STATE(4), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 5,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [198] = 18,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(45), 1,
      anon_sym_RPAREN,
    STATE(17), 1,
      sym_atom,
    STATE(19), 1,
      sym_primary_term,
    STATE(22), 1,
      sym_quoted_atom,
    STATE(40), 1,
      sym_mul_expr,
    STATE(44), 1,
      sym_add_expr,
    STATE(50), 1,
      sym_pipe_expr,
    STATE(61), 1,
      sym_term,
    STATE(5), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 5,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [258] = 18,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    STATE(17), 1,
      sym_atom,
    STATE(19), 1,
      sym_primary_term,
    STATE(22), 1,
      sym_quoted_atom,
    STATE(40), 1,
      sym_mul_expr,
    STATE(44), 1,
      sym_add_expr,
    STATE(50), 1,
      sym_pipe_expr,
    STATE(58), 1,
      sym_term,
    STATE(71), 1,
      sym_goals,
    STATE(6), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 5,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [318] = 17,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    STATE(17), 1,
      sym_atom,
    STATE(19), 1,
      sym_primary_term,
    STATE(22), 1,
      sym_quoted_atom,
    STATE(40), 1,
      sym_mul_expr,
    STATE(44), 1,
      sym_add_expr,
    STATE(50), 1,
      sym_pipe_expr,
    STATE(74), 1,
      sym_term,
    STATE(7), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 5,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [375] = 17,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    STATE(17), 1,
      sym_atom,
    STATE(19), 1,
      sym_primary_term,
    STATE(22), 1,
      sym_quoted_atom,
    STATE(40), 1,
      sym_mul_expr,
    STATE(44), 1,
      sym_add_expr,
    STATE(50), 1,
      sym_pipe_expr,
    STATE(75), 1,
      sym_term,
    STATE(8), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 5,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [432] = 17,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    STATE(17), 1,
      sym_atom,
    STATE(19), 1,
      sym_primary_term,
    STATE(22), 1,
      sym_quoted_atom,
    STATE(40), 1,
      sym_mul_expr,
    STATE(44), 1,
      sym_add_expr,
    STATE(50), 1,
      sym_pipe_expr,
    STATE(68), 1,
      sym_term,
    STATE(9), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 5,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [489] = 17,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    STATE(17), 1,
      sym_atom,
    STATE(19), 1,
      sym_primary_term,
    STATE(22), 1,
      sym_quoted_atom,
    STATE(40), 1,
      sym_mul_expr,
    STATE(44), 1,
      sym_add_expr,
    STATE(50), 1,
      sym_pipe_expr,
    STATE(52), 1,
      sym_term,
    STATE(10), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 5,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [546] = 9,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(51), 1,
      anon_sym_AT,
    STATE(67), 1,
      sym_comp_op,
    ACTIONS(49), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    ACTIONS(53), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(55), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(11), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(47), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [586] = 8,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(69), 1,
      sym_comp_op,
    ACTIONS(53), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(55), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(12), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(57), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [623] = 8,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(72), 1,
      sym_comp_op,
    ACTIONS(49), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    ACTIONS(53), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(55), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(13), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(47), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [660] = 15,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    STATE(17), 1,
      sym_atom,
    STATE(19), 1,
      sym_primary_term,
    STATE(22), 1,
      sym_quoted_atom,
    STATE(40), 1,
      sym_mul_expr,
    STATE(48), 1,
      sym_add_expr,
    STATE(14), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 5,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [711] = 14,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    STATE(17), 1,
      sym_atom,
    STATE(19), 1,
      sym_primary_term,
    STATE(22), 1,
      sym_quoted_atom,
    STATE(41), 1,
      sym_mul_expr,
    STATE(15), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 5,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [759] = 13,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    STATE(17), 1,
      sym_atom,
    STATE(22), 1,
      sym_quoted_atom,
    STATE(37), 1,
      sym_primary_term,
    STATE(16), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 5,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [804] = 6,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(61), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(17), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(47), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [833] = 7,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(65), 1,
      anon_sym_STAR,
    ACTIONS(68), 1,
      anon_sym_SLASH,
    ACTIONS(71), 1,
      anon_sym_PIPE,
    STATE(18), 3,
      sym_line_comment,
      sym_block_comment,
      aux_sym_mul_expr_repeat1,
    ACTIONS(63), 8,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [864] = 8,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(75), 1,
      anon_sym_STAR,
    ACTIONS(77), 1,
      anon_sym_SLASH,
    ACTIONS(79), 1,
      anon_sym_PIPE,
    STATE(21), 1,
      aux_sym_mul_expr_repeat1,
    STATE(19), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(73), 8,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [897] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(83), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(20), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(81), 10,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [924] = 8,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(75), 1,
      anon_sym_STAR,
    ACTIONS(77), 1,
      anon_sym_SLASH,
    ACTIONS(87), 1,
      anon_sym_PIPE,
    STATE(18), 1,
      aux_sym_mul_expr_repeat1,
    STATE(21), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(85), 8,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [957] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(91), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(22), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(89), 10,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [984] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(95), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(23), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(93), 10,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1011] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(99), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(24), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(97), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1037] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(103), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(25), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(101), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1063] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(107), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(26), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(105), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1089] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(111), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(27), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(109), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1115] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(59), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(28), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(57), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1141] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(115), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(29), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(113), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1167] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(119), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(30), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(117), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1193] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(49), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(31), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(47), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1219] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(123), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(32), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(121), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1245] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(127), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(33), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(125), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1271] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(131), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(34), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(129), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1297] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(135), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(35), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(133), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1323] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(139), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(36), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(137), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1349] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(71), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(37), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(63), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1375] = 7,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(145), 1,
      anon_sym_PIPE,
    STATE(39), 1,
      aux_sym_add_expr_repeat1,
    ACTIONS(143), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(38), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(141), 6,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1404] = 6,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(152), 1,
      anon_sym_PIPE,
    ACTIONS(149), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(39), 3,
      sym_line_comment,
      sym_block_comment,
      aux_sym_add_expr_repeat1,
    ACTIONS(147), 6,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1431] = 7,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(156), 1,
      anon_sym_PIPE,
    STATE(38), 1,
      aux_sym_add_expr_repeat1,
    ACTIONS(143), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(40), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(154), 6,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1460] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(152), 1,
      anon_sym_PIPE,
    STATE(41), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(147), 8,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1484] = 7,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(160), 1,
      anon_sym_PIPE_GT,
    ACTIONS(162), 1,
      anon_sym_PIPE,
    STATE(43), 1,
      aux_sym_pipe_expr_repeat1,
    STATE(42), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(158), 5,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1511] = 6,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(166), 1,
      anon_sym_PIPE_GT,
    ACTIONS(169), 1,
      anon_sym_PIPE,
    STATE(43), 3,
      sym_line_comment,
      sym_block_comment,
      aux_sym_pipe_expr_repeat1,
    ACTIONS(164), 5,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1536] = 7,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(160), 1,
      anon_sym_PIPE_GT,
    ACTIONS(173), 1,
      anon_sym_PIPE,
    STATE(42), 1,
      aux_sym_pipe_expr_repeat1,
    STATE(44), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(171), 5,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1563] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(45), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(175), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_unquoted_atom,
      anon_sym_SQUOTE,
      sym_variable,
      sym_number,
  [1583] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(46), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(177), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_unquoted_atom,
      anon_sym_SQUOTE,
      sym_variable,
      sym_number,
  [1603] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(47), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(179), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_unquoted_atom,
      anon_sym_SQUOTE,
      sym_variable,
      sym_number,
  [1623] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(169), 1,
      anon_sym_PIPE,
    STATE(48), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(164), 6,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1645] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(49), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(181), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_unquoted_atom,
      anon_sym_SQUOTE,
      sym_variable,
      sym_number,
  [1665] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(50), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(183), 6,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_RBRACK,
  [1684] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(187), 1,
      anon_sym_COMMA,
    STATE(51), 3,
      sym_line_comment,
      sym_block_comment,
      aux_sym_goals_repeat1,
    ACTIONS(185), 4,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_RBRACK,
  [1705] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(52), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(185), 5,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_RBRACK,
  [1723] = 7,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    ACTIONS(192), 1,
      anon_sym_PIPE,
    ACTIONS(194), 1,
      anon_sym_RBRACK,
    STATE(54), 1,
      aux_sym_goals_repeat1,
    STATE(53), 2,
      sym_line_comment,
      sym_block_comment,
  [1746] = 7,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    ACTIONS(196), 1,
      anon_sym_PIPE,
    ACTIONS(198), 1,
      anon_sym_RBRACK,
    STATE(51), 1,
      aux_sym_goals_repeat1,
    STATE(54), 2,
      sym_line_comment,
      sym_block_comment,
  [1769] = 6,
    ACTIONS(200), 1,
      anon_sym_SQUOTE,
    ACTIONS(204), 1,
      anon_sym_PERCENT,
    ACTIONS(206), 1,
      anon_sym_SLASH_STAR,
    STATE(57), 1,
      aux_sym_quoted_atom_repeat1,
    ACTIONS(202), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
    STATE(55), 2,
      sym_line_comment,
      sym_block_comment,
  [1790] = 5,
    ACTIONS(204), 1,
      anon_sym_PERCENT,
    ACTIONS(206), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(208), 1,
      anon_sym_SQUOTE,
    ACTIONS(210), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
    STATE(56), 3,
      sym_line_comment,
      sym_block_comment,
      aux_sym_quoted_atom_repeat1,
  [1809] = 6,
    ACTIONS(204), 1,
      anon_sym_PERCENT,
    ACTIONS(206), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(213), 1,
      anon_sym_SQUOTE,
    STATE(56), 1,
      aux_sym_quoted_atom_repeat1,
    ACTIONS(202), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
    STATE(57), 2,
      sym_line_comment,
      sym_block_comment,
  [1830] = 6,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    ACTIONS(215), 1,
      anon_sym_DOT,
    STATE(62), 1,
      aux_sym_goals_repeat1,
    STATE(58), 2,
      sym_line_comment,
      sym_block_comment,
  [1850] = 4,
    ACTIONS(204), 1,
      anon_sym_PERCENT,
    ACTIONS(206), 1,
      anon_sym_SLASH_STAR,
    STATE(59), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(217), 3,
      anon_sym_SQUOTE,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
  [1866] = 6,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    ACTIONS(219), 1,
      anon_sym_RPAREN,
    STATE(51), 1,
      aux_sym_goals_repeat1,
    STATE(60), 2,
      sym_line_comment,
      sym_block_comment,
  [1886] = 6,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      aux_sym_goals_repeat1,
    STATE(61), 2,
      sym_line_comment,
      sym_block_comment,
  [1906] = 6,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(190), 1,
      anon_sym_COMMA,
    ACTIONS(223), 1,
      anon_sym_DOT,
    STATE(51), 1,
      aux_sym_goals_repeat1,
    STATE(62), 2,
      sym_line_comment,
      sym_block_comment,
  [1926] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(225), 2,
      sym_variable,
      sym_number,
    STATE(63), 2,
      sym_line_comment,
      sym_block_comment,
  [1941] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(227), 1,
      anon_sym_DOT,
    ACTIONS(229), 1,
      anon_sym_COLON_DASH,
    STATE(64), 2,
      sym_line_comment,
      sym_block_comment,
  [1958] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(231), 1,
      ts_builtin_sym_end,
    STATE(65), 2,
      sym_line_comment,
      sym_block_comment,
  [1972] = 4,
    ACTIONS(204), 1,
      anon_sym_PERCENT,
    ACTIONS(206), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(233), 1,
      aux_sym_block_comment_token1,
    STATE(66), 2,
      sym_line_comment,
      sym_block_comment,
  [1986] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(235), 1,
      sym_number,
    STATE(67), 2,
      sym_line_comment,
      sym_block_comment,
  [2000] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(237), 1,
      anon_sym_RBRACK,
    STATE(68), 2,
      sym_line_comment,
      sym_block_comment,
  [2014] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(239), 1,
      sym_number,
    STATE(69), 2,
      sym_line_comment,
      sym_block_comment,
  [2028] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(241), 1,
      sym_number,
    STATE(70), 2,
      sym_line_comment,
      sym_block_comment,
  [2042] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(243), 1,
      anon_sym_DOT,
    STATE(71), 2,
      sym_line_comment,
      sym_block_comment,
  [2056] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(245), 1,
      sym_variable,
    STATE(72), 2,
      sym_line_comment,
      sym_block_comment,
  [2070] = 4,
    ACTIONS(204), 1,
      anon_sym_PERCENT,
    ACTIONS(206), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(247), 1,
      aux_sym_line_comment_token1,
    STATE(73), 2,
      sym_line_comment,
      sym_block_comment,
  [2084] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(249), 1,
      anon_sym_RBRACK,
    STATE(74), 2,
      sym_line_comment,
      sym_block_comment,
  [2098] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(251), 1,
      anon_sym_RPAREN,
    STATE(75), 2,
      sym_line_comment,
      sym_block_comment,
  [2112] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(253), 1,
      anon_sym_SLASH,
    STATE(76), 2,
      sym_line_comment,
      sym_block_comment,
  [2126] = 1,
    ACTIONS(255), 1,
      ts_builtin_sym_end,
  [2130] = 1,
    ACTIONS(257), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 68,
  [SMALL_STATE(4)] = 138,
  [SMALL_STATE(5)] = 198,
  [SMALL_STATE(6)] = 258,
  [SMALL_STATE(7)] = 318,
  [SMALL_STATE(8)] = 375,
  [SMALL_STATE(9)] = 432,
  [SMALL_STATE(10)] = 489,
  [SMALL_STATE(11)] = 546,
  [SMALL_STATE(12)] = 586,
  [SMALL_STATE(13)] = 623,
  [SMALL_STATE(14)] = 660,
  [SMALL_STATE(15)] = 711,
  [SMALL_STATE(16)] = 759,
  [SMALL_STATE(17)] = 804,
  [SMALL_STATE(18)] = 833,
  [SMALL_STATE(19)] = 864,
  [SMALL_STATE(20)] = 897,
  [SMALL_STATE(21)] = 924,
  [SMALL_STATE(22)] = 957,
  [SMALL_STATE(23)] = 984,
  [SMALL_STATE(24)] = 1011,
  [SMALL_STATE(25)] = 1037,
  [SMALL_STATE(26)] = 1063,
  [SMALL_STATE(27)] = 1089,
  [SMALL_STATE(28)] = 1115,
  [SMALL_STATE(29)] = 1141,
  [SMALL_STATE(30)] = 1167,
  [SMALL_STATE(31)] = 1193,
  [SMALL_STATE(32)] = 1219,
  [SMALL_STATE(33)] = 1245,
  [SMALL_STATE(34)] = 1271,
  [SMALL_STATE(35)] = 1297,
  [SMALL_STATE(36)] = 1323,
  [SMALL_STATE(37)] = 1349,
  [SMALL_STATE(38)] = 1375,
  [SMALL_STATE(39)] = 1404,
  [SMALL_STATE(40)] = 1431,
  [SMALL_STATE(41)] = 1460,
  [SMALL_STATE(42)] = 1484,
  [SMALL_STATE(43)] = 1511,
  [SMALL_STATE(44)] = 1536,
  [SMALL_STATE(45)] = 1563,
  [SMALL_STATE(46)] = 1583,
  [SMALL_STATE(47)] = 1603,
  [SMALL_STATE(48)] = 1623,
  [SMALL_STATE(49)] = 1645,
  [SMALL_STATE(50)] = 1665,
  [SMALL_STATE(51)] = 1684,
  [SMALL_STATE(52)] = 1705,
  [SMALL_STATE(53)] = 1723,
  [SMALL_STATE(54)] = 1746,
  [SMALL_STATE(55)] = 1769,
  [SMALL_STATE(56)] = 1790,
  [SMALL_STATE(57)] = 1809,
  [SMALL_STATE(58)] = 1830,
  [SMALL_STATE(59)] = 1850,
  [SMALL_STATE(60)] = 1866,
  [SMALL_STATE(61)] = 1886,
  [SMALL_STATE(62)] = 1906,
  [SMALL_STATE(63)] = 1926,
  [SMALL_STATE(64)] = 1941,
  [SMALL_STATE(65)] = 1958,
  [SMALL_STATE(66)] = 1972,
  [SMALL_STATE(67)] = 1986,
  [SMALL_STATE(68)] = 2000,
  [SMALL_STATE(69)] = 2014,
  [SMALL_STATE(70)] = 2028,
  [SMALL_STATE(71)] = 2042,
  [SMALL_STATE(72)] = 2056,
  [SMALL_STATE(73)] = 2070,
  [SMALL_STATE(74)] = 2084,
  [SMALL_STATE(75)] = 2098,
  [SMALL_STATE(76)] = 2112,
  [SMALL_STATE(77)] = 2126,
  [SMALL_STATE(78)] = 2130,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(8),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(4),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(22),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(55),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(11),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(13),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_term, 1),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary_term, 1),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range_var, 3),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range_var, 3),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_mul_expr_repeat1, 2),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mul_expr_repeat1, 2), SHIFT_REPEAT(16),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mul_expr_repeat1, 2), SHIFT_REPEAT(16),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_mul_expr_repeat1, 2),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mul_expr, 1),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mul_expr, 1),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 3),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_atom, 3),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mul_expr, 2),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mul_expr, 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom, 1),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_atom, 1),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 2),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_atom, 2),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 5),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range_var, 5),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range_var, 5),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 4),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_default_var, 3),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_default_var, 3),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 4),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 3),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 3),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 5),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expr, 3),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren_expr, 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 6),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 6),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_expr, 2),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_add_expr, 2),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_add_expr_repeat1, 2),
  [149] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_add_expr_repeat1, 2), SHIFT_REPEAT(15),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_add_expr_repeat1, 2),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_expr, 1),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_add_expr, 1),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipe_expr, 2),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipe_expr, 2),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pipe_expr_repeat1, 2),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pipe_expr_repeat1, 2), SHIFT_REPEAT(14),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pipe_expr_repeat1, 2),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipe_expr, 1),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipe_expr, 1),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clause, 1),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fact, 2),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 1),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_goals_repeat1, 2),
  [187] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_goals_repeat1, 2), SHIFT_REPEAT(10),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_atom_repeat1, 2),
  [210] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_atom_repeat1, 2), SHIFT_REPEAT(59),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goals, 1),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_atom_repeat1, 1),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goals, 2),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comp_op, 1),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [231] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_comment, 3),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_cadhr_lang(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
