#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 77
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_DOT = 1,
  anon_sym_COLON_DASH = 2,
  anon_sym_COMMA = 3,
  anon_sym_PIPE_GT = 4,
  anon_sym_PLUS = 5,
  anon_sym_DASH = 6,
  anon_sym_STAR = 7,
  anon_sym_SLASH = 8,
  anon_sym_LPAREN = 9,
  anon_sym_RPAREN = 10,
  anon_sym_LT_EQ = 11,
  anon_sym_GT_EQ = 12,
  anon_sym_LT = 13,
  anon_sym_GT = 14,
  anon_sym_LBRACK = 15,
  anon_sym_PIPE = 16,
  anon_sym_RBRACK = 17,
  sym_unquoted_atom = 18,
  anon_sym_SQUOTE = 19,
  aux_sym_quoted_atom_token1 = 20,
  sym_escape_sequence = 21,
  sym_variable = 22,
  sym_number = 23,
  anon_sym_PERCENT = 24,
  aux_sym_line_comment_token1 = 25,
  anon_sym_SLASH_STAR = 26,
  aux_sym_block_comment_token1 = 27,
  sym_source_file = 28,
  sym_clause = 29,
  sym_fact = 30,
  sym_rule = 31,
  sym_goals = 32,
  sym_term = 33,
  sym_pipe_expr = 34,
  sym_add_expr = 35,
  sym_mul_expr = 36,
  sym_primary_term = 37,
  sym_paren_expr = 38,
  sym_range_var = 39,
  sym_comp_op = 40,
  sym_list = 41,
  sym_struct = 42,
  sym_atom = 43,
  sym_quoted_atom = 44,
  sym_line_comment = 45,
  sym_block_comment = 46,
  aux_sym_source_file_repeat1 = 47,
  aux_sym_goals_repeat1 = 48,
  aux_sym_pipe_expr_repeat1 = 49,
  aux_sym_add_expr_repeat1 = 50,
  aux_sym_mul_expr_repeat1 = 51,
  aux_sym_quoted_atom_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DOT] = ".",
  [anon_sym_COLON_DASH] = ":-",
  [anon_sym_COMMA] = ",",
  [anon_sym_PIPE_GT] = "|>",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LBRACK] = "[",
  [anon_sym_PIPE] = "|",
  [anon_sym_RBRACK] = "]",
  [sym_unquoted_atom] = "unquoted_atom",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_atom_token1] = "quoted_atom_token1",
  [sym_escape_sequence] = "escape_sequence",
  [sym_variable] = "variable",
  [sym_number] = "number",
  [anon_sym_PERCENT] = "%",
  [aux_sym_line_comment_token1] = "line_comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_block_comment_token1] = "block_comment_token1",
  [sym_source_file] = "source_file",
  [sym_clause] = "clause",
  [sym_fact] = "fact",
  [sym_rule] = "rule",
  [sym_goals] = "goals",
  [sym_term] = "term",
  [sym_pipe_expr] = "pipe_expr",
  [sym_add_expr] = "add_expr",
  [sym_mul_expr] = "mul_expr",
  [sym_primary_term] = "primary_term",
  [sym_paren_expr] = "paren_expr",
  [sym_range_var] = "range_var",
  [sym_comp_op] = "comp_op",
  [sym_list] = "list",
  [sym_struct] = "struct",
  [sym_atom] = "atom",
  [sym_quoted_atom] = "quoted_atom",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_goals_repeat1] = "goals_repeat1",
  [aux_sym_pipe_expr_repeat1] = "pipe_expr_repeat1",
  [aux_sym_add_expr_repeat1] = "add_expr_repeat1",
  [aux_sym_mul_expr_repeat1] = "mul_expr_repeat1",
  [aux_sym_quoted_atom_repeat1] = "quoted_atom_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_COLON_DASH] = anon_sym_COLON_DASH,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_PIPE_GT] = anon_sym_PIPE_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_unquoted_atom] = sym_unquoted_atom,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_atom_token1] = aux_sym_quoted_atom_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_variable] = sym_variable,
  [sym_number] = sym_number,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [aux_sym_line_comment_token1] = aux_sym_line_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_block_comment_token1] = aux_sym_block_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym_clause] = sym_clause,
  [sym_fact] = sym_fact,
  [sym_rule] = sym_rule,
  [sym_goals] = sym_goals,
  [sym_term] = sym_term,
  [sym_pipe_expr] = sym_pipe_expr,
  [sym_add_expr] = sym_add_expr,
  [sym_mul_expr] = sym_mul_expr,
  [sym_primary_term] = sym_primary_term,
  [sym_paren_expr] = sym_paren_expr,
  [sym_range_var] = sym_range_var,
  [sym_comp_op] = sym_comp_op,
  [sym_list] = sym_list,
  [sym_struct] = sym_struct,
  [sym_atom] = sym_atom,
  [sym_quoted_atom] = sym_quoted_atom,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_goals_repeat1] = aux_sym_goals_repeat1,
  [aux_sym_pipe_expr_repeat1] = aux_sym_pipe_expr_repeat1,
  [aux_sym_add_expr_repeat1] = aux_sym_add_expr_repeat1,
  [aux_sym_mul_expr_repeat1] = aux_sym_mul_expr_repeat1,
  [aux_sym_quoted_atom_repeat1] = aux_sym_quoted_atom_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_unquoted_atom] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_atom_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_block_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_fact] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_goals] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_pipe_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_add_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_mul_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_term] = {
    .visible = true,
    .named = true,
  },
  [sym_paren_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_range_var] = {
    .visible = true,
    .named = true,
  },
  [sym_comp_op] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_goals_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pipe_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_add_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mul_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_atom_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      if (lookahead == '%') ADVANCE(36);
      if (lookahead == '\'') ADVANCE(29);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == ')') ADVANCE(20);
      if (lookahead == '*') ADVANCE(17);
      if (lookahead == '+') ADVANCE(15);
      if (lookahead == ',') ADVANCE(13);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '.') ADVANCE(11);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead == ':') ADVANCE(6);
      if (lookahead == '<') ADVANCE(23);
      if (lookahead == '>') ADVANCE(24);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == ']') ADVANCE(27);
      if (lookahead == '|') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(34);
      END_STATE();
    case 1:
      if (lookahead == '%') ADVANCE(38);
      if (lookahead == '\'') ADVANCE(29);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 2:
      if (lookahead == '%') ADVANCE(37);
      if (lookahead == '*') ADVANCE(47);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(2);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(43);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(47);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(44);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == '\n' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 't') ADVANCE(33);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 9:
      if (eof) ADVANCE(10);
      if (lookahead == '%') ADVANCE(36);
      if (lookahead == '\'') ADVANCE(29);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == ')') ADVANCE(20);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == ']') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(34);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON_DASH);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_PIPE_GT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(43);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(21);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(22);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '>') ADVANCE(14);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_unquoted_atom);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == '%') ADVANCE(38);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == '*') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == '*') ADVANCE(47);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(32);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '%') ADVANCE(39);
      if (lookahead == '/') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '*') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead == '*') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(4);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(32);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_block_comment_token1);
      if (lookahead == '*') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(4);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 9},
  [2] = {.lex_state = 9},
  [3] = {.lex_state = 9},
  [4] = {.lex_state = 9},
  [5] = {.lex_state = 9},
  [6] = {.lex_state = 9},
  [7] = {.lex_state = 9},
  [8] = {.lex_state = 9},
  [9] = {.lex_state = 9},
  [10] = {.lex_state = 9},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 9},
  [15] = {.lex_state = 9},
  [16] = {.lex_state = 9},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 9},
  [45] = {.lex_state = 9},
  [46] = {.lex_state = 9},
  [47] = {.lex_state = 9},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 9},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 9},
  [67] = {.lex_state = 9},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 40},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {(TSStateId)(-1)},
  [76] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_line_comment] = STATE(0),
    [sym_block_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_COLON_DASH] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_PIPE_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_unquoted_atom] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [1] = {
    [sym_source_file] = STATE(71),
    [sym_clause] = STATE(46),
    [sym_fact] = STATE(45),
    [sym_rule] = STATE(45),
    [sym_term] = STATE(62),
    [sym_pipe_expr] = STATE(49),
    [sym_add_expr] = STATE(42),
    [sym_mul_expr] = STATE(39),
    [sym_primary_term] = STATE(22),
    [sym_paren_expr] = STATE(36),
    [sym_range_var] = STATE(36),
    [sym_list] = STATE(36),
    [sym_struct] = STATE(36),
    [sym_atom] = STATE(20),
    [sym_quoted_atom] = STATE(19),
    [sym_line_comment] = STATE(1),
    [sym_block_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [sym_unquoted_atom] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [sym_variable] = ACTIONS(17),
    [sym_number] = ACTIONS(19),
    [anon_sym_PERCENT] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 21,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(19), 1,
      sym_quoted_atom,
    STATE(20), 1,
      sym_atom,
    STATE(22), 1,
      sym_primary_term,
    STATE(39), 1,
      sym_mul_expr,
    STATE(42), 1,
      sym_add_expr,
    STATE(46), 1,
      sym_clause,
    STATE(49), 1,
      sym_pipe_expr,
    STATE(62), 1,
      sym_term,
    STATE(2), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(45), 2,
      sym_fact,
      sym_rule,
    STATE(36), 4,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [69] = 20,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(28), 1,
      anon_sym_LBRACK,
    ACTIONS(31), 1,
      sym_unquoted_atom,
    ACTIONS(34), 1,
      anon_sym_SQUOTE,
    ACTIONS(37), 1,
      sym_variable,
    ACTIONS(40), 1,
      sym_number,
    STATE(19), 1,
      sym_quoted_atom,
    STATE(20), 1,
      sym_atom,
    STATE(22), 1,
      sym_primary_term,
    STATE(39), 1,
      sym_mul_expr,
    STATE(42), 1,
      sym_add_expr,
    STATE(46), 1,
      sym_clause,
    STATE(49), 1,
      sym_pipe_expr,
    STATE(62), 1,
      sym_term,
    STATE(45), 2,
      sym_fact,
      sym_rule,
    STATE(3), 3,
      sym_line_comment,
      sym_block_comment,
      aux_sym_source_file_repeat1,
    STATE(36), 4,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [136] = 18,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(43), 1,
      anon_sym_RBRACK,
    STATE(19), 1,
      sym_quoted_atom,
    STATE(20), 1,
      sym_atom,
    STATE(22), 1,
      sym_primary_term,
    STATE(39), 1,
      sym_mul_expr,
    STATE(42), 1,
      sym_add_expr,
    STATE(49), 1,
      sym_pipe_expr,
    STATE(54), 1,
      sym_term,
    STATE(4), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(36), 4,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [195] = 18,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    ACTIONS(45), 1,
      anon_sym_RPAREN,
    STATE(19), 1,
      sym_quoted_atom,
    STATE(20), 1,
      sym_atom,
    STATE(22), 1,
      sym_primary_term,
    STATE(39), 1,
      sym_mul_expr,
    STATE(42), 1,
      sym_add_expr,
    STATE(49), 1,
      sym_pipe_expr,
    STATE(60), 1,
      sym_term,
    STATE(5), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(36), 4,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [254] = 18,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    STATE(19), 1,
      sym_quoted_atom,
    STATE(20), 1,
      sym_atom,
    STATE(22), 1,
      sym_primary_term,
    STATE(39), 1,
      sym_mul_expr,
    STATE(42), 1,
      sym_add_expr,
    STATE(49), 1,
      sym_pipe_expr,
    STATE(57), 1,
      sym_term,
    STATE(65), 1,
      sym_goals,
    STATE(6), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(36), 4,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [313] = 17,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    STATE(19), 1,
      sym_quoted_atom,
    STATE(20), 1,
      sym_atom,
    STATE(22), 1,
      sym_primary_term,
    STATE(39), 1,
      sym_mul_expr,
    STATE(42), 1,
      sym_add_expr,
    STATE(49), 1,
      sym_pipe_expr,
    STATE(72), 1,
      sym_term,
    STATE(7), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(36), 4,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [369] = 17,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    STATE(19), 1,
      sym_quoted_atom,
    STATE(20), 1,
      sym_atom,
    STATE(22), 1,
      sym_primary_term,
    STATE(39), 1,
      sym_mul_expr,
    STATE(42), 1,
      sym_add_expr,
    STATE(49), 1,
      sym_pipe_expr,
    STATE(73), 1,
      sym_term,
    STATE(8), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(36), 4,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [425] = 17,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    STATE(19), 1,
      sym_quoted_atom,
    STATE(20), 1,
      sym_atom,
    STATE(22), 1,
      sym_primary_term,
    STATE(39), 1,
      sym_mul_expr,
    STATE(42), 1,
      sym_add_expr,
    STATE(49), 1,
      sym_pipe_expr,
    STATE(69), 1,
      sym_term,
    STATE(9), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(36), 4,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [481] = 17,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    STATE(19), 1,
      sym_quoted_atom,
    STATE(20), 1,
      sym_atom,
    STATE(22), 1,
      sym_primary_term,
    STATE(39), 1,
      sym_mul_expr,
    STATE(42), 1,
      sym_add_expr,
    STATE(49), 1,
      sym_pipe_expr,
    STATE(51), 1,
      sym_term,
    STATE(10), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(36), 4,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [537] = 8,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(67), 1,
      sym_comp_op,
    ACTIONS(49), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    ACTIONS(51), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(53), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(11), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(47), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [574] = 8,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(66), 1,
      sym_comp_op,
    ACTIONS(51), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(53), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(57), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(12), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(55), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [611] = 8,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(64), 1,
      sym_comp_op,
    ACTIONS(51), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(53), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(57), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(13), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(55), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [648] = 15,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    STATE(19), 1,
      sym_quoted_atom,
    STATE(20), 1,
      sym_atom,
    STATE(22), 1,
      sym_primary_term,
    STATE(39), 1,
      sym_mul_expr,
    STATE(48), 1,
      sym_add_expr,
    STATE(14), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(36), 4,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [698] = 14,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    STATE(19), 1,
      sym_quoted_atom,
    STATE(20), 1,
      sym_atom,
    STATE(22), 1,
      sym_primary_term,
    STATE(40), 1,
      sym_mul_expr,
    STATE(15), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(36), 4,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [745] = 13,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      sym_variable,
    ACTIONS(19), 1,
      sym_number,
    STATE(19), 1,
      sym_quoted_atom,
    STATE(20), 1,
      sym_atom,
    STATE(24), 1,
      sym_primary_term,
    STATE(16), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(36), 4,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
  [789] = 8,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(61), 1,
      anon_sym_STAR,
    ACTIONS(63), 1,
      anon_sym_SLASH,
    ACTIONS(65), 1,
      anon_sym_PIPE,
    STATE(23), 1,
      aux_sym_mul_expr_repeat1,
    STATE(17), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(59), 8,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [822] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(69), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(18), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(67), 10,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [849] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(73), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(19), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(71), 10,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [876] = 6,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(75), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(20), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(55), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [905] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(79), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(21), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(77), 10,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [932] = 8,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(61), 1,
      anon_sym_STAR,
    ACTIONS(63), 1,
      anon_sym_SLASH,
    ACTIONS(83), 1,
      anon_sym_PIPE,
    STATE(17), 1,
      aux_sym_mul_expr_repeat1,
    STATE(22), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(81), 8,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [965] = 7,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(87), 1,
      anon_sym_STAR,
    ACTIONS(90), 1,
      anon_sym_SLASH,
    ACTIONS(93), 1,
      anon_sym_PIPE,
    STATE(23), 3,
      sym_line_comment,
      sym_block_comment,
      aux_sym_mul_expr_repeat1,
    ACTIONS(85), 8,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [996] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(93), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(24), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(85), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1022] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(97), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(25), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(95), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1048] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(101), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(26), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(99), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1074] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(105), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(27), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(103), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1100] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(109), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(28), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(107), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1126] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(49), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(29), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(47), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1152] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(113), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(30), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(111), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1178] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(117), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(31), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(115), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1204] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(121), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(32), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(119), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1230] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(125), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(33), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(123), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1256] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(129), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(34), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(127), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1282] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(133), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(35), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(131), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1308] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(57), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(36), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(55), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1334] = 7,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(139), 1,
      anon_sym_PIPE,
    STATE(38), 1,
      aux_sym_add_expr_repeat1,
    ACTIONS(137), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(37), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(135), 6,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1363] = 6,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(146), 1,
      anon_sym_PIPE,
    ACTIONS(143), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(38), 3,
      sym_line_comment,
      sym_block_comment,
      aux_sym_add_expr_repeat1,
    ACTIONS(141), 6,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1390] = 7,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(150), 1,
      anon_sym_PIPE,
    STATE(37), 1,
      aux_sym_add_expr_repeat1,
    ACTIONS(137), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(39), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(148), 6,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1419] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(146), 1,
      anon_sym_PIPE,
    STATE(40), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(141), 8,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1443] = 6,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(154), 1,
      anon_sym_PIPE_GT,
    ACTIONS(157), 1,
      anon_sym_PIPE,
    STATE(41), 3,
      sym_line_comment,
      sym_block_comment,
      aux_sym_pipe_expr_repeat1,
    ACTIONS(152), 5,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1468] = 7,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(161), 1,
      anon_sym_PIPE_GT,
    ACTIONS(163), 1,
      anon_sym_PIPE,
    STATE(43), 1,
      aux_sym_pipe_expr_repeat1,
    STATE(42), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(159), 5,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1495] = 7,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(161), 1,
      anon_sym_PIPE_GT,
    ACTIONS(167), 1,
      anon_sym_PIPE,
    STATE(41), 1,
      aux_sym_pipe_expr_repeat1,
    STATE(43), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(165), 5,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1522] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(44), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(169), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_unquoted_atom,
      anon_sym_SQUOTE,
      sym_variable,
      sym_number,
  [1542] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(45), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(171), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_unquoted_atom,
      anon_sym_SQUOTE,
      sym_variable,
      sym_number,
  [1562] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(46), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(173), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_unquoted_atom,
      anon_sym_SQUOTE,
      sym_variable,
      sym_number,
  [1582] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(47), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(175), 7,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_unquoted_atom,
      anon_sym_SQUOTE,
      sym_variable,
      sym_number,
  [1602] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(157), 1,
      anon_sym_PIPE,
    STATE(48), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(152), 6,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1624] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(49), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(177), 6,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_RBRACK,
  [1643] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(181), 1,
      anon_sym_COMMA,
    STATE(50), 3,
      sym_line_comment,
      sym_block_comment,
      aux_sym_goals_repeat1,
    ACTIONS(179), 4,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_RBRACK,
  [1664] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(51), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(179), 5,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_RBRACK,
  [1682] = 6,
    ACTIONS(184), 1,
      anon_sym_SQUOTE,
    ACTIONS(188), 1,
      anon_sym_PERCENT,
    ACTIONS(190), 1,
      anon_sym_SLASH_STAR,
    STATE(56), 1,
      aux_sym_quoted_atom_repeat1,
    ACTIONS(186), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
    STATE(52), 2,
      sym_line_comment,
      sym_block_comment,
  [1703] = 5,
    ACTIONS(188), 1,
      anon_sym_PERCENT,
    ACTIONS(190), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(192), 1,
      anon_sym_SQUOTE,
    ACTIONS(194), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
    STATE(53), 3,
      sym_line_comment,
      sym_block_comment,
      aux_sym_quoted_atom_repeat1,
  [1722] = 7,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    ACTIONS(199), 1,
      anon_sym_PIPE,
    ACTIONS(201), 1,
      anon_sym_RBRACK,
    STATE(55), 1,
      aux_sym_goals_repeat1,
    STATE(54), 2,
      sym_line_comment,
      sym_block_comment,
  [1745] = 7,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    ACTIONS(203), 1,
      anon_sym_PIPE,
    ACTIONS(205), 1,
      anon_sym_RBRACK,
    STATE(50), 1,
      aux_sym_goals_repeat1,
    STATE(55), 2,
      sym_line_comment,
      sym_block_comment,
  [1768] = 6,
    ACTIONS(188), 1,
      anon_sym_PERCENT,
    ACTIONS(190), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(207), 1,
      anon_sym_SQUOTE,
    STATE(53), 1,
      aux_sym_quoted_atom_repeat1,
    ACTIONS(186), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
    STATE(56), 2,
      sym_line_comment,
      sym_block_comment,
  [1789] = 6,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    ACTIONS(209), 1,
      anon_sym_DOT,
    STATE(61), 1,
      aux_sym_goals_repeat1,
    STATE(57), 2,
      sym_line_comment,
      sym_block_comment,
  [1809] = 4,
    ACTIONS(188), 1,
      anon_sym_PERCENT,
    ACTIONS(190), 1,
      anon_sym_SLASH_STAR,
    STATE(58), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(211), 3,
      anon_sym_SQUOTE,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
  [1825] = 6,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    ACTIONS(213), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      aux_sym_goals_repeat1,
    STATE(59), 2,
      sym_line_comment,
      sym_block_comment,
  [1845] = 6,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    ACTIONS(215), 1,
      anon_sym_RPAREN,
    STATE(59), 1,
      aux_sym_goals_repeat1,
    STATE(60), 2,
      sym_line_comment,
      sym_block_comment,
  [1865] = 6,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    ACTIONS(217), 1,
      anon_sym_DOT,
    STATE(50), 1,
      aux_sym_goals_repeat1,
    STATE(61), 2,
      sym_line_comment,
      sym_block_comment,
  [1885] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(219), 1,
      anon_sym_DOT,
    ACTIONS(221), 1,
      anon_sym_COLON_DASH,
    STATE(62), 2,
      sym_line_comment,
      sym_block_comment,
  [1902] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(223), 2,
      sym_variable,
      sym_number,
    STATE(63), 2,
      sym_line_comment,
      sym_block_comment,
  [1917] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(225), 1,
      sym_variable,
    STATE(64), 2,
      sym_line_comment,
      sym_block_comment,
  [1931] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(227), 1,
      anon_sym_DOT,
    STATE(65), 2,
      sym_line_comment,
      sym_block_comment,
  [1945] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(229), 1,
      sym_number,
    STATE(66), 2,
      sym_line_comment,
      sym_block_comment,
  [1959] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(231), 1,
      sym_number,
    STATE(67), 2,
      sym_line_comment,
      sym_block_comment,
  [1973] = 4,
    ACTIONS(188), 1,
      anon_sym_PERCENT,
    ACTIONS(190), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(233), 1,
      aux_sym_block_comment_token1,
    STATE(68), 2,
      sym_line_comment,
      sym_block_comment,
  [1987] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(235), 1,
      anon_sym_RBRACK,
    STATE(69), 2,
      sym_line_comment,
      sym_block_comment,
  [2001] = 4,
    ACTIONS(188), 1,
      anon_sym_PERCENT,
    ACTIONS(190), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(237), 1,
      aux_sym_line_comment_token1,
    STATE(70), 2,
      sym_line_comment,
      sym_block_comment,
  [2015] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(239), 1,
      ts_builtin_sym_end,
    STATE(71), 2,
      sym_line_comment,
      sym_block_comment,
  [2029] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(241), 1,
      anon_sym_RBRACK,
    STATE(72), 2,
      sym_line_comment,
      sym_block_comment,
  [2043] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(243), 1,
      anon_sym_RPAREN,
    STATE(73), 2,
      sym_line_comment,
      sym_block_comment,
  [2057] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(245), 1,
      anon_sym_SLASH,
    STATE(74), 2,
      sym_line_comment,
      sym_block_comment,
  [2071] = 1,
    ACTIONS(247), 1,
      ts_builtin_sym_end,
  [2075] = 1,
    ACTIONS(249), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 69,
  [SMALL_STATE(4)] = 136,
  [SMALL_STATE(5)] = 195,
  [SMALL_STATE(6)] = 254,
  [SMALL_STATE(7)] = 313,
  [SMALL_STATE(8)] = 369,
  [SMALL_STATE(9)] = 425,
  [SMALL_STATE(10)] = 481,
  [SMALL_STATE(11)] = 537,
  [SMALL_STATE(12)] = 574,
  [SMALL_STATE(13)] = 611,
  [SMALL_STATE(14)] = 648,
  [SMALL_STATE(15)] = 698,
  [SMALL_STATE(16)] = 745,
  [SMALL_STATE(17)] = 789,
  [SMALL_STATE(18)] = 822,
  [SMALL_STATE(19)] = 849,
  [SMALL_STATE(20)] = 876,
  [SMALL_STATE(21)] = 905,
  [SMALL_STATE(22)] = 932,
  [SMALL_STATE(23)] = 965,
  [SMALL_STATE(24)] = 996,
  [SMALL_STATE(25)] = 1022,
  [SMALL_STATE(26)] = 1048,
  [SMALL_STATE(27)] = 1074,
  [SMALL_STATE(28)] = 1100,
  [SMALL_STATE(29)] = 1126,
  [SMALL_STATE(30)] = 1152,
  [SMALL_STATE(31)] = 1178,
  [SMALL_STATE(32)] = 1204,
  [SMALL_STATE(33)] = 1230,
  [SMALL_STATE(34)] = 1256,
  [SMALL_STATE(35)] = 1282,
  [SMALL_STATE(36)] = 1308,
  [SMALL_STATE(37)] = 1334,
  [SMALL_STATE(38)] = 1363,
  [SMALL_STATE(39)] = 1390,
  [SMALL_STATE(40)] = 1419,
  [SMALL_STATE(41)] = 1443,
  [SMALL_STATE(42)] = 1468,
  [SMALL_STATE(43)] = 1495,
  [SMALL_STATE(44)] = 1522,
  [SMALL_STATE(45)] = 1542,
  [SMALL_STATE(46)] = 1562,
  [SMALL_STATE(47)] = 1582,
  [SMALL_STATE(48)] = 1602,
  [SMALL_STATE(49)] = 1624,
  [SMALL_STATE(50)] = 1643,
  [SMALL_STATE(51)] = 1664,
  [SMALL_STATE(52)] = 1682,
  [SMALL_STATE(53)] = 1703,
  [SMALL_STATE(54)] = 1722,
  [SMALL_STATE(55)] = 1745,
  [SMALL_STATE(56)] = 1768,
  [SMALL_STATE(57)] = 1789,
  [SMALL_STATE(58)] = 1809,
  [SMALL_STATE(59)] = 1825,
  [SMALL_STATE(60)] = 1845,
  [SMALL_STATE(61)] = 1865,
  [SMALL_STATE(62)] = 1885,
  [SMALL_STATE(63)] = 1902,
  [SMALL_STATE(64)] = 1917,
  [SMALL_STATE(65)] = 1931,
  [SMALL_STATE(66)] = 1945,
  [SMALL_STATE(67)] = 1959,
  [SMALL_STATE(68)] = 1973,
  [SMALL_STATE(69)] = 1987,
  [SMALL_STATE(70)] = 2001,
  [SMALL_STATE(71)] = 2015,
  [SMALL_STATE(72)] = 2029,
  [SMALL_STATE(73)] = 2043,
  [SMALL_STATE(74)] = 2057,
  [SMALL_STATE(75)] = 2071,
  [SMALL_STATE(76)] = 2075,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(8),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(4),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(19),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(52),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(12),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(13),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range_var, 3),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range_var, 3),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_term, 1),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary_term, 1),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mul_expr, 2),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mul_expr, 2),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 2),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_atom, 2),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom, 1),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_atom, 1),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 3),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_atom, 3),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mul_expr, 1),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mul_expr, 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_mul_expr_repeat1, 2),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mul_expr_repeat1, 2), SHIFT_REPEAT(16),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mul_expr_repeat1, 2), SHIFT_REPEAT(16),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_mul_expr_repeat1, 2),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 5),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 4),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 6),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 6),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 4),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 5),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 3),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 3),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range_var, 5),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range_var, 5),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expr, 3),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren_expr, 3),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_expr, 2),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_add_expr, 2),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_add_expr_repeat1, 2),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_add_expr_repeat1, 2), SHIFT_REPEAT(15),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_add_expr_repeat1, 2),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_expr, 1),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_add_expr, 1),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pipe_expr_repeat1, 2),
  [154] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pipe_expr_repeat1, 2), SHIFT_REPEAT(14),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pipe_expr_repeat1, 2),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipe_expr, 1),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipe_expr, 1),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipe_expr, 2),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipe_expr, 2),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clause, 1),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fact, 2),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 1),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_goals_repeat1, 2),
  [181] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_goals_repeat1, 2), SHIFT_REPEAT(10),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_atom_repeat1, 2),
  [194] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_atom_repeat1, 2), SHIFT_REPEAT(58),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goals, 1),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_atom_repeat1, 1),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goals, 2),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comp_op, 1),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [237] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [239] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [245] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_comment, 3),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_cadhr_lang(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
