#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 85
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 59
#define ALIAS_COUNT 0
#define TOKEN_COUNT 31
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_DOT = 1,
  anon_sym_COLON_DASH = 2,
  anon_sym_COMMA = 3,
  anon_sym_PIPE_GT = 4,
  anon_sym_PLUS = 5,
  anon_sym_DASH = 6,
  anon_sym_STAR = 7,
  anon_sym_SLASH = 8,
  anon_sym_AT = 9,
  anon_sym_LPAREN = 10,
  anon_sym_RPAREN = 11,
  anon_sym_LT_EQ = 12,
  anon_sym_GT_EQ = 13,
  anon_sym_LT = 14,
  anon_sym_GT = 15,
  anon_sym_LBRACK = 16,
  anon_sym_PIPE = 17,
  anon_sym_RBRACK = 18,
  sym_unquoted_atom = 19,
  anon_sym_SQUOTE = 20,
  aux_sym_quoted_atom_token1 = 21,
  sym_escape_sequence = 22,
  anon_sym_DQUOTE = 23,
  aux_sym_string_literal_token1 = 24,
  sym_variable = 25,
  sym_number = 26,
  anon_sym_PERCENT = 27,
  aux_sym_line_comment_token1 = 28,
  anon_sym_SLASH_STAR = 29,
  aux_sym_block_comment_token1 = 30,
  sym_source_file = 31,
  sym_clause = 32,
  sym_fact = 33,
  sym_rule = 34,
  sym_goals = 35,
  sym_term = 36,
  sym_pipe_expr = 37,
  sym_add_expr = 38,
  sym_mul_expr = 39,
  sym_primary_term = 40,
  sym_default_var = 41,
  sym_paren_expr = 42,
  sym_range_var = 43,
  sym_comp_op = 44,
  sym_list = 45,
  sym_struct = 46,
  sym_atom = 47,
  sym_quoted_atom = 48,
  sym_string_literal = 49,
  sym_line_comment = 50,
  sym_block_comment = 51,
  aux_sym_source_file_repeat1 = 52,
  aux_sym_goals_repeat1 = 53,
  aux_sym_pipe_expr_repeat1 = 54,
  aux_sym_add_expr_repeat1 = 55,
  aux_sym_mul_expr_repeat1 = 56,
  aux_sym_quoted_atom_repeat1 = 57,
  aux_sym_string_literal_repeat1 = 58,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DOT] = ".",
  [anon_sym_COLON_DASH] = ":-",
  [anon_sym_COMMA] = ",",
  [anon_sym_PIPE_GT] = "|>",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_AT] = "@",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LBRACK] = "[",
  [anon_sym_PIPE] = "|",
  [anon_sym_RBRACK] = "]",
  [sym_unquoted_atom] = "unquoted_atom",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_atom_token1] = "quoted_atom_token1",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [sym_variable] = "variable",
  [sym_number] = "number",
  [anon_sym_PERCENT] = "%",
  [aux_sym_line_comment_token1] = "line_comment_token1",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_block_comment_token1] = "block_comment_token1",
  [sym_source_file] = "source_file",
  [sym_clause] = "clause",
  [sym_fact] = "fact",
  [sym_rule] = "rule",
  [sym_goals] = "goals",
  [sym_term] = "term",
  [sym_pipe_expr] = "pipe_expr",
  [sym_add_expr] = "add_expr",
  [sym_mul_expr] = "mul_expr",
  [sym_primary_term] = "primary_term",
  [sym_default_var] = "default_var",
  [sym_paren_expr] = "paren_expr",
  [sym_range_var] = "range_var",
  [sym_comp_op] = "comp_op",
  [sym_list] = "list",
  [sym_struct] = "struct",
  [sym_atom] = "atom",
  [sym_quoted_atom] = "quoted_atom",
  [sym_string_literal] = "string_literal",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_goals_repeat1] = "goals_repeat1",
  [aux_sym_pipe_expr_repeat1] = "pipe_expr_repeat1",
  [aux_sym_add_expr_repeat1] = "add_expr_repeat1",
  [aux_sym_mul_expr_repeat1] = "mul_expr_repeat1",
  [aux_sym_quoted_atom_repeat1] = "quoted_atom_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_COLON_DASH] = anon_sym_COLON_DASH,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_PIPE_GT] = anon_sym_PIPE_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_unquoted_atom] = sym_unquoted_atom,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_atom_token1] = aux_sym_quoted_atom_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [sym_variable] = sym_variable,
  [sym_number] = sym_number,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [aux_sym_line_comment_token1] = aux_sym_line_comment_token1,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_block_comment_token1] = aux_sym_block_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym_clause] = sym_clause,
  [sym_fact] = sym_fact,
  [sym_rule] = sym_rule,
  [sym_goals] = sym_goals,
  [sym_term] = sym_term,
  [sym_pipe_expr] = sym_pipe_expr,
  [sym_add_expr] = sym_add_expr,
  [sym_mul_expr] = sym_mul_expr,
  [sym_primary_term] = sym_primary_term,
  [sym_default_var] = sym_default_var,
  [sym_paren_expr] = sym_paren_expr,
  [sym_range_var] = sym_range_var,
  [sym_comp_op] = sym_comp_op,
  [sym_list] = sym_list,
  [sym_struct] = sym_struct,
  [sym_atom] = sym_atom,
  [sym_quoted_atom] = sym_quoted_atom,
  [sym_string_literal] = sym_string_literal,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_goals_repeat1] = aux_sym_goals_repeat1,
  [aux_sym_pipe_expr_repeat1] = aux_sym_pipe_expr_repeat1,
  [aux_sym_add_expr_repeat1] = aux_sym_add_expr_repeat1,
  [aux_sym_mul_expr_repeat1] = aux_sym_mul_expr_repeat1,
  [aux_sym_quoted_atom_repeat1] = aux_sym_quoted_atom_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_unquoted_atom] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_atom_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_block_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_fact] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_goals] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_pipe_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_add_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_mul_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_term] = {
    .visible = true,
    .named = true,
  },
  [sym_default_var] = {
    .visible = true,
    .named = true,
  },
  [sym_paren_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_range_var] = {
    .visible = true,
    .named = true,
  },
  [sym_comp_op] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_struct] = {
    .visible = true,
    .named = true,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_goals_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pipe_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_add_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mul_expr_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_atom_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '"') ADVANCE(37);
      if (lookahead == '%') ADVANCE(45);
      if (lookahead == '\'') ADVANCE(32);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == '*') ADVANCE(19);
      if (lookahead == '+') ADVANCE(17);
      if (lookahead == ',') ADVANCE(15);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == '.') ADVANCE(13);
      if (lookahead == '/') ADVANCE(20);
      if (lookahead == ':') ADVANCE(7);
      if (lookahead == '<') ADVANCE(26);
      if (lookahead == '>') ADVANCE(27);
      if (lookahead == '@') ADVANCE(21);
      if (lookahead == '[') ADVANCE(28);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead == ']') ADVANCE(30);
      if (lookahead == '|') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(41);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(37);
      if (lookahead == '%') ADVANCE(47);
      if (lookahead == '/') ADVANCE(39);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0) ADVANCE(40);
      END_STATE();
    case 2:
      if (lookahead == '%') ADVANCE(48);
      if (lookahead == '\'') ADVANCE(32);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 3:
      if (lookahead == '%') ADVANCE(46);
      if (lookahead == '*') ADVANCE(58);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(53);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(58);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(54);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 't') ADVANCE(36);
      END_STATE();
    case 9:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 10:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '"') ADVANCE(37);
      if (lookahead == '%') ADVANCE(45);
      if (lookahead == '\'') ADVANCE(32);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == '-') ADVANCE(9);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '[') ADVANCE(28);
      if (lookahead == ']') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(11)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(41);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COLON_DASH);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_PIPE_GT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(53);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(25);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '>') ADVANCE(16);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_unquoted_atom);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == '%') ADVANCE(48);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead == '*') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_quoted_atom_token1);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '%') ADVANCE(47);
      if (lookahead == '/') ADVANCE(39);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(40);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '*') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_number);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == '*') ADVANCE(58);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(40);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(35);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '%') ADVANCE(49);
      if (lookahead == '/') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '*') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead == '*') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(5);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(40);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(35);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_block_comment_token1);
      if (lookahead == '*') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(5);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 11},
  [7] = {.lex_state = 11},
  [8] = {.lex_state = 11},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 11},
  [11] = {.lex_state = 11},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 11},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 11},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 11},
  [46] = {.lex_state = 11},
  [47] = {.lex_state = 11},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 11},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 11},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 11},
  [74] = {.lex_state = 11},
  [75] = {.lex_state = 11},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 50},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {(TSStateId)(-1)},
  [84] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_line_comment] = STATE(0),
    [sym_block_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_COLON_DASH] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_PIPE_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_unquoted_atom] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [1] = {
    [sym_source_file] = STATE(78),
    [sym_clause] = STATE(45),
    [sym_fact] = STATE(46),
    [sym_rule] = STATE(46),
    [sym_term] = STATE(70),
    [sym_pipe_expr] = STATE(52),
    [sym_add_expr] = STATE(48),
    [sym_mul_expr] = STATE(42),
    [sym_primary_term] = STATE(20),
    [sym_default_var] = STATE(31),
    [sym_paren_expr] = STATE(31),
    [sym_range_var] = STATE(31),
    [sym_list] = STATE(31),
    [sym_struct] = STATE(31),
    [sym_atom] = STATE(17),
    [sym_quoted_atom] = STATE(21),
    [sym_string_literal] = STATE(31),
    [sym_line_comment] = STATE(1),
    [sym_block_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [sym_unquoted_atom] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [sym_variable] = ACTIONS(19),
    [sym_number] = ACTIONS(21),
    [anon_sym_PERCENT] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 22,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      sym_variable,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(17), 1,
      sym_atom,
    STATE(20), 1,
      sym_primary_term,
    STATE(21), 1,
      sym_quoted_atom,
    STATE(42), 1,
      sym_mul_expr,
    STATE(45), 1,
      sym_clause,
    STATE(48), 1,
      sym_add_expr,
    STATE(52), 1,
      sym_pipe_expr,
    STATE(70), 1,
      sym_term,
    STATE(2), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(46), 2,
      sym_fact,
      sym_rule,
    STATE(31), 6,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
      sym_string_literal,
  [74] = 21,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(30), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      sym_unquoted_atom,
    ACTIONS(36), 1,
      anon_sym_SQUOTE,
    ACTIONS(39), 1,
      anon_sym_DQUOTE,
    ACTIONS(42), 1,
      sym_variable,
    ACTIONS(45), 1,
      sym_number,
    STATE(17), 1,
      sym_atom,
    STATE(20), 1,
      sym_primary_term,
    STATE(21), 1,
      sym_quoted_atom,
    STATE(42), 1,
      sym_mul_expr,
    STATE(45), 1,
      sym_clause,
    STATE(48), 1,
      sym_add_expr,
    STATE(52), 1,
      sym_pipe_expr,
    STATE(70), 1,
      sym_term,
    STATE(46), 2,
      sym_fact,
      sym_rule,
    STATE(3), 3,
      sym_line_comment,
      sym_block_comment,
      aux_sym_source_file_repeat1,
    STATE(31), 6,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
      sym_string_literal,
  [146] = 19,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      sym_variable,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(48), 1,
      anon_sym_RBRACK,
    STATE(17), 1,
      sym_atom,
    STATE(20), 1,
      sym_primary_term,
    STATE(21), 1,
      sym_quoted_atom,
    STATE(42), 1,
      sym_mul_expr,
    STATE(48), 1,
      sym_add_expr,
    STATE(52), 1,
      sym_pipe_expr,
    STATE(57), 1,
      sym_term,
    STATE(4), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 6,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
      sym_string_literal,
  [210] = 19,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      sym_variable,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(50), 1,
      anon_sym_RPAREN,
    STATE(17), 1,
      sym_atom,
    STATE(20), 1,
      sym_primary_term,
    STATE(21), 1,
      sym_quoted_atom,
    STATE(42), 1,
      sym_mul_expr,
    STATE(48), 1,
      sym_add_expr,
    STATE(52), 1,
      sym_pipe_expr,
    STATE(63), 1,
      sym_term,
    STATE(5), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 6,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
      sym_string_literal,
  [274] = 19,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      sym_variable,
    ACTIONS(21), 1,
      sym_number,
    STATE(17), 1,
      sym_atom,
    STATE(20), 1,
      sym_primary_term,
    STATE(21), 1,
      sym_quoted_atom,
    STATE(42), 1,
      sym_mul_expr,
    STATE(48), 1,
      sym_add_expr,
    STATE(52), 1,
      sym_pipe_expr,
    STATE(65), 1,
      sym_term,
    STATE(80), 1,
      sym_goals,
    STATE(6), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 6,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
      sym_string_literal,
  [338] = 18,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      sym_variable,
    ACTIONS(21), 1,
      sym_number,
    STATE(17), 1,
      sym_atom,
    STATE(20), 1,
      sym_primary_term,
    STATE(21), 1,
      sym_quoted_atom,
    STATE(42), 1,
      sym_mul_expr,
    STATE(48), 1,
      sym_add_expr,
    STATE(52), 1,
      sym_pipe_expr,
    STATE(79), 1,
      sym_term,
    STATE(7), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 6,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
      sym_string_literal,
  [399] = 18,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      sym_variable,
    ACTIONS(21), 1,
      sym_number,
    STATE(17), 1,
      sym_atom,
    STATE(20), 1,
      sym_primary_term,
    STATE(21), 1,
      sym_quoted_atom,
    STATE(42), 1,
      sym_mul_expr,
    STATE(48), 1,
      sym_add_expr,
    STATE(52), 1,
      sym_pipe_expr,
    STATE(81), 1,
      sym_term,
    STATE(8), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 6,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
      sym_string_literal,
  [460] = 18,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      sym_variable,
    ACTIONS(21), 1,
      sym_number,
    STATE(17), 1,
      sym_atom,
    STATE(20), 1,
      sym_primary_term,
    STATE(21), 1,
      sym_quoted_atom,
    STATE(42), 1,
      sym_mul_expr,
    STATE(48), 1,
      sym_add_expr,
    STATE(52), 1,
      sym_pipe_expr,
    STATE(71), 1,
      sym_term,
    STATE(9), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 6,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
      sym_string_literal,
  [521] = 18,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      sym_variable,
    ACTIONS(21), 1,
      sym_number,
    STATE(17), 1,
      sym_atom,
    STATE(20), 1,
      sym_primary_term,
    STATE(21), 1,
      sym_quoted_atom,
    STATE(42), 1,
      sym_mul_expr,
    STATE(48), 1,
      sym_add_expr,
    STATE(52), 1,
      sym_pipe_expr,
    STATE(54), 1,
      sym_term,
    STATE(10), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 6,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
      sym_string_literal,
  [582] = 16,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      sym_variable,
    ACTIONS(21), 1,
      sym_number,
    STATE(17), 1,
      sym_atom,
    STATE(20), 1,
      sym_primary_term,
    STATE(21), 1,
      sym_quoted_atom,
    STATE(42), 1,
      sym_mul_expr,
    STATE(51), 1,
      sym_add_expr,
    STATE(11), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 6,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
      sym_string_literal,
  [637] = 9,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(56), 1,
      anon_sym_AT,
    STATE(74), 1,
      sym_comp_op,
    ACTIONS(54), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    ACTIONS(58), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(60), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(12), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(52), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [677] = 15,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      sym_variable,
    ACTIONS(21), 1,
      sym_number,
    STATE(17), 1,
      sym_atom,
    STATE(20), 1,
      sym_primary_term,
    STATE(21), 1,
      sym_quoted_atom,
    STATE(43), 1,
      sym_mul_expr,
    STATE(13), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 6,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
      sym_string_literal,
  [729] = 8,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(75), 1,
      sym_comp_op,
    ACTIONS(58), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(60), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(64), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(14), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(62), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [766] = 8,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(76), 1,
      sym_comp_op,
    ACTIONS(54), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    ACTIONS(58), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(60), 2,
      anon_sym_LT,
      anon_sym_GT,
    STATE(15), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(52), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [803] = 14,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 1,
      sym_unquoted_atom,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(19), 1,
      sym_variable,
    ACTIONS(21), 1,
      sym_number,
    STATE(17), 1,
      sym_atom,
    STATE(21), 1,
      sym_quoted_atom,
    STATE(24), 1,
      sym_primary_term,
    STATE(16), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(31), 6,
      sym_default_var,
      sym_paren_expr,
      sym_range_var,
      sym_list,
      sym_struct,
      sym_string_literal,
  [852] = 6,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(66), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(17), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(52), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [881] = 7,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(70), 1,
      anon_sym_STAR,
    ACTIONS(73), 1,
      anon_sym_SLASH,
    ACTIONS(76), 1,
      anon_sym_PIPE,
    STATE(18), 3,
      sym_line_comment,
      sym_block_comment,
      aux_sym_mul_expr_repeat1,
    ACTIONS(68), 8,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [912] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(80), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(19), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(78), 10,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [939] = 8,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(84), 1,
      anon_sym_STAR,
    ACTIONS(86), 1,
      anon_sym_SLASH,
    ACTIONS(88), 1,
      anon_sym_PIPE,
    STATE(22), 1,
      aux_sym_mul_expr_repeat1,
    STATE(20), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(82), 8,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [972] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(92), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(21), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(90), 10,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [999] = 8,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(84), 1,
      anon_sym_STAR,
    ACTIONS(86), 1,
      anon_sym_SLASH,
    ACTIONS(96), 1,
      anon_sym_PIPE,
    STATE(18), 1,
      aux_sym_mul_expr_repeat1,
    STATE(22), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(94), 8,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1032] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(100), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(23), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(98), 10,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1059] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(76), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(24), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(68), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1085] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(104), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(25), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(102), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1111] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(108), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(26), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(106), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1137] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(112), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(27), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(110), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1163] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(116), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(28), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(114), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1189] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(120), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(29), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(118), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1215] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(124), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(30), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(122), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1241] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(54), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(31), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(52), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1267] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(128), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(32), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(126), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1293] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(132), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(33), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(130), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1319] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(64), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(34), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(62), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1345] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(136), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(35), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(134), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1371] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(140), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(36), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(138), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1397] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(144), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(37), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(142), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1423] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(148), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(38), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(146), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1449] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(152), 2,
      anon_sym_SLASH,
      anon_sym_PIPE,
    STATE(39), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(150), 9,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1475] = 6,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(159), 1,
      anon_sym_PIPE,
    ACTIONS(156), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(40), 3,
      sym_line_comment,
      sym_block_comment,
      aux_sym_add_expr_repeat1,
    ACTIONS(154), 6,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1502] = 7,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(165), 1,
      anon_sym_PIPE,
    STATE(40), 1,
      aux_sym_add_expr_repeat1,
    ACTIONS(163), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(41), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(161), 6,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1531] = 7,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(169), 1,
      anon_sym_PIPE,
    STATE(41), 1,
      aux_sym_add_expr_repeat1,
    ACTIONS(163), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(42), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(167), 6,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1560] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(159), 1,
      anon_sym_PIPE,
    STATE(43), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(154), 8,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1584] = 6,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(173), 1,
      anon_sym_PIPE_GT,
    ACTIONS(176), 1,
      anon_sym_PIPE,
    STATE(44), 3,
      sym_line_comment,
      sym_block_comment,
      aux_sym_pipe_expr_repeat1,
    ACTIONS(171), 5,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1609] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(45), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(178), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_unquoted_atom,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym_variable,
      sym_number,
  [1630] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(46), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(180), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_unquoted_atom,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym_variable,
      sym_number,
  [1651] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(47), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(182), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_unquoted_atom,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym_variable,
      sym_number,
  [1672] = 7,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(186), 1,
      anon_sym_PIPE_GT,
    ACTIONS(188), 1,
      anon_sym_PIPE,
    STATE(49), 1,
      aux_sym_pipe_expr_repeat1,
    STATE(48), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(184), 5,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1699] = 7,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(186), 1,
      anon_sym_PIPE_GT,
    ACTIONS(192), 1,
      anon_sym_PIPE,
    STATE(44), 1,
      aux_sym_pipe_expr_repeat1,
    STATE(49), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(190), 5,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1726] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(50), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(194), 8,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_unquoted_atom,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      sym_variable,
      sym_number,
  [1747] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(176), 1,
      anon_sym_PIPE,
    STATE(51), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(171), 6,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_PIPE_GT,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
  [1769] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(52), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(196), 6,
      anon_sym_DOT,
      anon_sym_COLON_DASH,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_RBRACK,
  [1788] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(200), 1,
      anon_sym_COMMA,
    STATE(53), 3,
      sym_line_comment,
      sym_block_comment,
      aux_sym_goals_repeat1,
    ACTIONS(198), 4,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_RBRACK,
  [1809] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(54), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(198), 5,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_RBRACK,
  [1827] = 6,
    ACTIONS(205), 1,
      anon_sym_DQUOTE,
    ACTIONS(207), 1,
      anon_sym_PERCENT,
    ACTIONS(209), 1,
      anon_sym_SLASH_STAR,
    STATE(61), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(203), 2,
      sym_escape_sequence,
      aux_sym_string_literal_token1,
    STATE(55), 2,
      sym_line_comment,
      sym_block_comment,
  [1848] = 5,
    ACTIONS(207), 1,
      anon_sym_PERCENT,
    ACTIONS(209), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(211), 1,
      anon_sym_SQUOTE,
    ACTIONS(213), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
    STATE(56), 3,
      sym_line_comment,
      sym_block_comment,
      aux_sym_quoted_atom_repeat1,
  [1867] = 7,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    ACTIONS(218), 1,
      anon_sym_PIPE,
    ACTIONS(220), 1,
      anon_sym_RBRACK,
    STATE(58), 1,
      aux_sym_goals_repeat1,
    STATE(57), 2,
      sym_line_comment,
      sym_block_comment,
  [1890] = 7,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    ACTIONS(222), 1,
      anon_sym_PIPE,
    ACTIONS(224), 1,
      anon_sym_RBRACK,
    STATE(53), 1,
      aux_sym_goals_repeat1,
    STATE(58), 2,
      sym_line_comment,
      sym_block_comment,
  [1913] = 6,
    ACTIONS(207), 1,
      anon_sym_PERCENT,
    ACTIONS(209), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(226), 1,
      anon_sym_SQUOTE,
    STATE(60), 1,
      aux_sym_quoted_atom_repeat1,
    ACTIONS(228), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
    STATE(59), 2,
      sym_line_comment,
      sym_block_comment,
  [1934] = 6,
    ACTIONS(207), 1,
      anon_sym_PERCENT,
    ACTIONS(209), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(230), 1,
      anon_sym_SQUOTE,
    STATE(56), 1,
      aux_sym_quoted_atom_repeat1,
    ACTIONS(228), 2,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
    STATE(60), 2,
      sym_line_comment,
      sym_block_comment,
  [1955] = 6,
    ACTIONS(207), 1,
      anon_sym_PERCENT,
    ACTIONS(209), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(232), 1,
      anon_sym_DQUOTE,
    STATE(62), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(203), 2,
      sym_escape_sequence,
      aux_sym_string_literal_token1,
    STATE(61), 2,
      sym_line_comment,
      sym_block_comment,
  [1976] = 5,
    ACTIONS(207), 1,
      anon_sym_PERCENT,
    ACTIONS(209), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(237), 1,
      anon_sym_DQUOTE,
    ACTIONS(234), 2,
      sym_escape_sequence,
      aux_sym_string_literal_token1,
    STATE(62), 3,
      sym_line_comment,
      sym_block_comment,
      aux_sym_string_literal_repeat1,
  [1995] = 6,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    ACTIONS(239), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      aux_sym_goals_repeat1,
    STATE(63), 2,
      sym_line_comment,
      sym_block_comment,
  [2015] = 4,
    ACTIONS(207), 1,
      anon_sym_PERCENT,
    ACTIONS(209), 1,
      anon_sym_SLASH_STAR,
    STATE(64), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(241), 3,
      anon_sym_SQUOTE,
      aux_sym_quoted_atom_token1,
      sym_escape_sequence,
  [2031] = 6,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    ACTIONS(243), 1,
      anon_sym_DOT,
    STATE(67), 1,
      aux_sym_goals_repeat1,
    STATE(65), 2,
      sym_line_comment,
      sym_block_comment,
  [2051] = 6,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      aux_sym_goals_repeat1,
    STATE(66), 2,
      sym_line_comment,
      sym_block_comment,
  [2071] = 6,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    ACTIONS(247), 1,
      anon_sym_DOT,
    STATE(53), 1,
      aux_sym_goals_repeat1,
    STATE(67), 2,
      sym_line_comment,
      sym_block_comment,
  [2091] = 4,
    ACTIONS(207), 1,
      anon_sym_PERCENT,
    ACTIONS(209), 1,
      anon_sym_SLASH_STAR,
    STATE(68), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(249), 3,
      sym_escape_sequence,
      anon_sym_DQUOTE,
      aux_sym_string_literal_token1,
  [2107] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(251), 2,
      sym_variable,
      sym_number,
    STATE(69), 2,
      sym_line_comment,
      sym_block_comment,
  [2122] = 5,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(253), 1,
      anon_sym_DOT,
    ACTIONS(255), 1,
      anon_sym_COLON_DASH,
    STATE(70), 2,
      sym_line_comment,
      sym_block_comment,
  [2139] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(257), 1,
      anon_sym_RBRACK,
    STATE(71), 2,
      sym_line_comment,
      sym_block_comment,
  [2153] = 4,
    ACTIONS(207), 1,
      anon_sym_PERCENT,
    ACTIONS(209), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(259), 1,
      aux_sym_block_comment_token1,
    STATE(72), 2,
      sym_line_comment,
      sym_block_comment,
  [2167] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(261), 1,
      sym_number,
    STATE(73), 2,
      sym_line_comment,
      sym_block_comment,
  [2181] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(263), 1,
      sym_number,
    STATE(74), 2,
      sym_line_comment,
      sym_block_comment,
  [2195] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(265), 1,
      sym_number,
    STATE(75), 2,
      sym_line_comment,
      sym_block_comment,
  [2209] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(267), 1,
      sym_variable,
    STATE(76), 2,
      sym_line_comment,
      sym_block_comment,
  [2223] = 4,
    ACTIONS(207), 1,
      anon_sym_PERCENT,
    ACTIONS(209), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(269), 1,
      aux_sym_line_comment_token1,
    STATE(77), 2,
      sym_line_comment,
      sym_block_comment,
  [2237] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(271), 1,
      ts_builtin_sym_end,
    STATE(78), 2,
      sym_line_comment,
      sym_block_comment,
  [2251] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(273), 1,
      anon_sym_RBRACK,
    STATE(79), 2,
      sym_line_comment,
      sym_block_comment,
  [2265] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(275), 1,
      anon_sym_DOT,
    STATE(80), 2,
      sym_line_comment,
      sym_block_comment,
  [2279] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(277), 1,
      anon_sym_RPAREN,
    STATE(81), 2,
      sym_line_comment,
      sym_block_comment,
  [2293] = 4,
    ACTIONS(3), 1,
      anon_sym_PERCENT,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(279), 1,
      anon_sym_SLASH,
    STATE(82), 2,
      sym_line_comment,
      sym_block_comment,
  [2307] = 1,
    ACTIONS(281), 1,
      ts_builtin_sym_end,
  [2311] = 1,
    ACTIONS(283), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 74,
  [SMALL_STATE(4)] = 146,
  [SMALL_STATE(5)] = 210,
  [SMALL_STATE(6)] = 274,
  [SMALL_STATE(7)] = 338,
  [SMALL_STATE(8)] = 399,
  [SMALL_STATE(9)] = 460,
  [SMALL_STATE(10)] = 521,
  [SMALL_STATE(11)] = 582,
  [SMALL_STATE(12)] = 637,
  [SMALL_STATE(13)] = 677,
  [SMALL_STATE(14)] = 729,
  [SMALL_STATE(15)] = 766,
  [SMALL_STATE(16)] = 803,
  [SMALL_STATE(17)] = 852,
  [SMALL_STATE(18)] = 881,
  [SMALL_STATE(19)] = 912,
  [SMALL_STATE(20)] = 939,
  [SMALL_STATE(21)] = 972,
  [SMALL_STATE(22)] = 999,
  [SMALL_STATE(23)] = 1032,
  [SMALL_STATE(24)] = 1059,
  [SMALL_STATE(25)] = 1085,
  [SMALL_STATE(26)] = 1111,
  [SMALL_STATE(27)] = 1137,
  [SMALL_STATE(28)] = 1163,
  [SMALL_STATE(29)] = 1189,
  [SMALL_STATE(30)] = 1215,
  [SMALL_STATE(31)] = 1241,
  [SMALL_STATE(32)] = 1267,
  [SMALL_STATE(33)] = 1293,
  [SMALL_STATE(34)] = 1319,
  [SMALL_STATE(35)] = 1345,
  [SMALL_STATE(36)] = 1371,
  [SMALL_STATE(37)] = 1397,
  [SMALL_STATE(38)] = 1423,
  [SMALL_STATE(39)] = 1449,
  [SMALL_STATE(40)] = 1475,
  [SMALL_STATE(41)] = 1502,
  [SMALL_STATE(42)] = 1531,
  [SMALL_STATE(43)] = 1560,
  [SMALL_STATE(44)] = 1584,
  [SMALL_STATE(45)] = 1609,
  [SMALL_STATE(46)] = 1630,
  [SMALL_STATE(47)] = 1651,
  [SMALL_STATE(48)] = 1672,
  [SMALL_STATE(49)] = 1699,
  [SMALL_STATE(50)] = 1726,
  [SMALL_STATE(51)] = 1747,
  [SMALL_STATE(52)] = 1769,
  [SMALL_STATE(53)] = 1788,
  [SMALL_STATE(54)] = 1809,
  [SMALL_STATE(55)] = 1827,
  [SMALL_STATE(56)] = 1848,
  [SMALL_STATE(57)] = 1867,
  [SMALL_STATE(58)] = 1890,
  [SMALL_STATE(59)] = 1913,
  [SMALL_STATE(60)] = 1934,
  [SMALL_STATE(61)] = 1955,
  [SMALL_STATE(62)] = 1976,
  [SMALL_STATE(63)] = 1995,
  [SMALL_STATE(64)] = 2015,
  [SMALL_STATE(65)] = 2031,
  [SMALL_STATE(66)] = 2051,
  [SMALL_STATE(67)] = 2071,
  [SMALL_STATE(68)] = 2091,
  [SMALL_STATE(69)] = 2107,
  [SMALL_STATE(70)] = 2122,
  [SMALL_STATE(71)] = 2139,
  [SMALL_STATE(72)] = 2153,
  [SMALL_STATE(73)] = 2167,
  [SMALL_STATE(74)] = 2181,
  [SMALL_STATE(75)] = 2195,
  [SMALL_STATE(76)] = 2209,
  [SMALL_STATE(77)] = 2223,
  [SMALL_STATE(78)] = 2237,
  [SMALL_STATE(79)] = 2251,
  [SMALL_STATE(80)] = 2265,
  [SMALL_STATE(81)] = 2279,
  [SMALL_STATE(82)] = 2293,
  [SMALL_STATE(83)] = 2307,
  [SMALL_STATE(84)] = 2311,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(8),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(4),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(21),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(59),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(55),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(12),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(15),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_term, 1),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary_term, 1),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range_var, 3),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range_var, 3),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_mul_expr_repeat1, 2),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_mul_expr_repeat1, 2), SHIFT_REPEAT(16),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mul_expr_repeat1, 2), SHIFT_REPEAT(16),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_mul_expr_repeat1, 2),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 3),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_atom, 3),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mul_expr, 1),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mul_expr, 1),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom, 1),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_atom, 1),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mul_expr, 2),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mul_expr, 2),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_atom, 2),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_atom, 2),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 5),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 5),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range_var, 5),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range_var, 5),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 5),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 4),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 4),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 4),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_struct, 3),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_struct, 3),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_default_var, 3),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_default_var, 3),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 6),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 6),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expr, 3),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren_expr, 3),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_add_expr_repeat1, 2),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_add_expr_repeat1, 2), SHIFT_REPEAT(13),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_add_expr_repeat1, 2),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_expr, 2),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_add_expr, 2),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_expr, 1),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_add_expr, 1),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pipe_expr_repeat1, 2),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pipe_expr_repeat1, 2), SHIFT_REPEAT(11),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pipe_expr_repeat1, 2),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clause, 1),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipe_expr, 1),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipe_expr, 1),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipe_expr, 2),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipe_expr, 2),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fact, 2),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 1),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_goals_repeat1, 2),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_goals_repeat1, 2), SHIFT_REPEAT(10),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [209] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_atom_repeat1, 2),
  [213] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_atom_repeat1, 2), SHIFT_REPEAT(64),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [234] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2), SHIFT_REPEAT(68),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_atom_repeat1, 1),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goals, 1),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_goals, 2),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 1),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comp_op, 1),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [269] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [271] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [279] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 2),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_comment, 3),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_cadhr_lang(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
